name = "MyExtensions"
uuid = "acfaa482-14be-4b33-895c-6016b1eaf7be"
authors = ["Olivier Gauthé <ogauthe@flatironinstitute.org>"]
version = "0.1.0"

[weakdeps]
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"

[extensions]
MyExtensionsTensorKitExt = "TensorKit"

[compat]
TensorKit = "0.14"
