name = "MyExtensions"
uuid = "acfaa482-14be-4b33-895c-6016b1eaf7be"
authors = ["Olivier Gauthé <ogauthe@flatironinstitute.org>"]
version = "0.1.0"

[weakdeps]
PEPSKit = "52969e89-939e-4361-9b68-9bc7cde4bdeb"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"

[extensions]
MyExtensionsTensorKitExt = "TensorKit"
MyExtensionsPEPSKitExt = ["PEPSKit", "TensorKit"]

[compat]
TensorKit = "0.14"
PEPSKit = "0.6"
